package repro

import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText
import org.jetbrains.amper.plugins.Output
import org.jetbrains.amper.plugins.TaskAction

@TaskAction
public fun generateResource(@Output outputDir: Path) {
    outputDir.createDirectories()
    outputDir.resolve("generated.txt").writeText("generated by repro-plugin\n")
}
